### ISSUE TITLE
Not using the correct meter

### ISSUE THREAD

**Issue by Maksim-us** [getterdone/FlumeWaterMeter#1]
I have 2 Flume meters in my flume app named "Home" and "123". In the SmartApps setting I've entered "Home" in the "Enter Flume location name assigned to Flume flow meter". However, the app seems to be detected the other meter.

**Comment by getterdone** [comment]
Hi thank you providing this issue. I was not able to test this case since I did not have two meters initially. Please use the newer updated Service Manager that handles multiple Flume meters along with the updated DH for the oneApp Smartthings app. https://github.com/getterdone/FlumeWaterMeter  prior files were moved to Legacy folder.

**Comment by getterdone** [comment]
updated OneApp SM handles multiple Flume meters, closing issue.

**Comment by Maksim-us** [comment]
Thank you. I replaced the code for the DH and the SmartApp in the IDE. However, when I go into the SmartApp in the ST app, there is no option to set the location name. I tried deleting and recreating the SmartApp in the ST app, but still no location name setting. And now, the sensor( "Flume Home")is no longer appearing in the list of my devices.
![Screenshot_20210104-155830](https://user-images.githubusercontent.com/29838695/103584035-75a1ae80-4ea6-11eb-8a4d-926ca04a26a7.jpg)

**Comment by getterdone** [comment]
Once you enter your login credentials and enter click Done this new implementation will find your Flume devices and assigned the names automatically based on the names you provided on the Flume ios/android app. So if your Flume device name is Flume-Home1, and Flume-Home2, in the OneApp Smartthings app, there should be two devices Flume-Home1-Flume Meter, and Flume-Home2-Flume Meter. https://community.smartthings.com/t/release-flume-water-meter-smartthings-smartapp-flume-water-meter-device-handler/172887/58

**Comment by Maksim-us** [comment]
Sorry, maybe I'm doing something wrong, but I can't figure it out. Once I enter my email/pw and click done, I see "processing" and get taken back to the list of all my smartapps. When I click on the "Flume Home" again, I am taken back to the same screen with credentials.

**Comment by getterdone** [comment]
Once you click Done in the screenshot above go back to your SmartThings app dashboard. The new Flume devices are now available. 
![14EA5073-5E5B-4FED-B069-D091A1AFA2BB](https://user-images.githubusercontent.com/1641341/103653218-3751d100-4f32-11eb-855d-ceb3f31521aa.png)

**Comment by Maksim-us** [comment]
Right, that's the issue. I don't see them in my list of devices.

**Comment by Maksim-us** [comment]
Interesting... They show up in the IDE but not in the app...

**Comment by getterdone** [comment]
Go to your dashboard where it shows ‘Home’ then tap middle of screen and drag down, this acts as a refresh and maybe forces devices to show. Then go to All devices and search for Flume 
![3A549026-178D-48FA-8A51-297D4288656D](https://user-images.githubusercontent.com/1641341/103655851-d9bf8380-4f35-11eb-89ab-cc9b3b26c07f.png)
![E6DA189B-19EF-4331-BDBC-93EBBB28B962](https://user-images.githubusercontent.com/1641341/103655854-d9bf8380-4f35-11eb-99f0-d327256d59fa.png)

If this doesn’t work uninstall/reinstall Samsung oneapp. If after reinstalling the SmartThings app they dont show up you will need to contact SmartThings to see what’s going on.

**Comment by Maksim-us** [comment]
Thanks. Tried that, and it didn't help. I am going to try to remove the devices from IDE and then remove the Smart app and DH handler and then add them from scratch.
